---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# debops.lxc default variables [[[
# ================================

# .. contents:: Sections
#    :local:
#
# .. include:: ../../../includes/global.rst


# APT packages [[[
# ----------------

# .. envvar:: lxc__base_packages [[[
#
# List of base APT packages to install for LXC support.
lxc__base_packages: [ 'lxc', 'debootstrap' ]

                                                                   # ]]]
# .. envvar:: lxc__packages [[[
#
# List of additional APT packages to install with LXC.
lxc__packages: []
                                                                   # ]]]
                                                                   # ]]]
# Unprivileged LXC containers [[[
# -------------------------------

# .. envvar:: lxc__root_subuid_start [[[
#
# Specify the first subUID of the unprivileged LXC containers managed by the
# ``root`` system account.
lxc__root_subuid_start: '{{ ansible_local.root_account.subuids[0]["start"]
                            if (ansible_local|d() and ansible_local.root_account|d() and
                                ansible_local.root_account.subuids|d())
                            else "100000" }}'

                                                                   # ]]]
# .. envvar:: lxc__root_subuid_count [[[
#
# Specify the number of subUIDs reserved for the unprivileged LXC containers
# managed by the ``root`` system account.
lxc__root_subuid_count: '{{ ansible_local.root_account.subuids[0]["count"]
                            if (ansible_local|d() and ansible_local.root_account|d() and
                                ansible_local.root_account.subuids|d())
                            else "65536" }}'

                                                                   # ]]]
# .. envvar:: lxc__root_subgid_start [[[
#
# Specify the first subGID of the unprivileged LXC containers managed by the
# ``root`` system account.
lxc__root_subgid_start: '{{ ansible_local.root_account.subgids[0]["start"]
                            if (ansible_local|d() and ansible_local.root_account|d() and
                                ansible_local.root_account.subgids|d())
                            else "100000" }}'

                                                                   # ]]]
# .. envvar:: lxc__root_subgid_count [[[
#
# Specify the number of subGIDs reserved for the unprivileged LXC containers
# managed by the ``root`` system account.
lxc__root_subgid_count: '{{ ansible_local.root_account.subgids[0]["count"]
                            if (ansible_local|d() and ansible_local.root_account|d() and
                                ansible_local.root_account.subgids|d())
                            else "65536" }}'
                                                                   # ]]]
                                                                   # ]]]
# System-wide configuration [[[
# -----------------------------

# These variables define contents of the configuration files in the
# :file:`/etc/lxc/` directory. See :ref:`lxc__ref_configuration` for more
# details.

# .. envvar:: lxc__default_configuration [[[
#
# The default LXC configuration files defined by the role.
lxc__default_configuration:

  - name: 'lxc'
    comment: 'System-wide LXC configuration options'
    options:

      - name: 'lxc.lxcpath'
        comment: 'Path where LXC containers are stored'
        value: '/var/lib/lxc'

      - name: 'lxc.cgroup.use'
        value: '@all'

      - name: 'lxc.default_config'
        comment: |
          Default configuration file used for new LXC containers if not
          specified otherwise
        value: '/etc/lxc/privileged.conf'

  - name: 'unprivileged'
    comment: |
      Default configuration for unprivileged LXC containers.
    options:

      - name: 'lxc.network.type'
        value: 'veth'

      - name: 'lxc.network.link'
        value: 'br0'

      - name: 'lxc.network.flags'
        value: 'up'

      - name: 'lxc.id_map_user'
        alias: 'lxc.id_map'
        value: 'u 0 {{ lxc__root_subuid_start }} {{ lxc__root_subuid_count }}'
        separator: True

      - name: 'lxc.id_map_group'
        alias: 'lxc.id_map'
        value: 'g 0 {{ lxc__root_subgid_start }} {{ lxc__root_subgid_count }}'

      - name: 'lxc.start.auto'
        value: '1'
        separator: True

      - name: 'lxc.cap.drop_secure'
        alias: 'lxc.cap.drop'
        value: 'mknod sys_rawio syslog wake_alarm'

  - name: 'privileged'
    comment: |
      Default configuration for privileged LXC containers
    options:

      - name: 'lxc.network.type'
        value: 'veth'

      - name: 'lxc.network.link'
        value: 'br0'

      - name: 'lxc.network.flags'
        value: 'up'

      - name: 'lxc.start.auto'
        value: '1'
        separator: True

      - name: 'lxc.cap.drop_secure'
        alias: 'lxc.cap.drop'
        value: 'mknod sys_rawio syslog wake_alarm'

  - name: 'external-internal'
    comment: |
      Default configuration for privileged LXC containers with multiple network
      interfaces
    options:

      - name: 'lxc.network.type_net0'
        alias: 'lxc.network.type'
        value: 'veth'

      - name: 'lxc.network.link_net0'
        alias: 'lxc.network.link'
        value: 'br0'

      - name: 'lxc.network.flags_net0'
        alias: 'lxc.network.flags'
        value: 'up'

      - name: 'lxc.network.type_net1'
        alias: 'lxc.network.type'
        value: 'veth'
        separator: True

      - name: 'lxc.network.link_net1'
        alias: 'lxc.network.link'
        value: 'br1'

      - name: 'lxc.network.flags_net1'
        alias: 'lxc.network.flags'
        value: 'up'

      - name: 'lxc.start.auto'
        value: '1'
        separator: True

      - name: 'lxc.cap.drop_secure'
        alias: 'lxc.cap.drop'
        value: 'mknod sys_rawio syslog wake_alarm'

                                                                   # ]]]
# .. envvar:: lxc__configuration [[[
#
# List of LXC configuration files which should be present on all hosts in the
# Ansible inventory.
lxc__configuration: []

                                                                   # ]]]
# .. envvar:: lxc__group_configuration [[[
#
# List of LXC configuration files which should be present on hosts in
# a specific Ansible inventory group.
lxc__group_configuration: []

                                                                   # ]]]
# .. envvar:: lxc__host_configuration [[[
#
# List of LXC configuration files which should be present on specific hosts in
# the Ansible inventory.
lxc__host_configuration: []

                                                                   # ]]]
# .. envvar:: lxc__combined_configuration [[[
#
# The variable that combines all of the configuration lists and is used in the
# role tasks.
lxc__combined_configuration: '{{ lxc__default_configuration
                                 + lxc__configuration
                                 + lxc__group_configuration
                                 + lxc__host_configuration }}'
                                                                   # ]]]
                                                                   # ]]]
# Configuration for other Ansible roles [[[
# -----------------------------------------

# .. envvar:: lxc__apt_preferences__dependent_list [[[
#
# Configuration for the :ref:`debops.apt_preferences` role.
lxc__apt_preferences__dependent_list: []

                                                                   # ]]]
# .. envvar:: lxc__ferm__dependent_rules [[[
#
# Configuration for the :ref:`debops.ferm` role.
lxc__ferm__dependent_rules:

  - type: 'custom'
    by_role: 'debops.lxc'
    filename: 'lxc_bootp_checksum'
    weight: '30'
    rule_state: 'absent'

  - type: 'custom'
    by_role: 'debops.lxc'
    name: 'bootp_checksum'
    weight: '30'
    rules: |
      # Add checksums to BOOTP packets for LXC containers
      # https://www.redhat.com/archives/libvir-list/2010-August/msg00035.html
      @hook post "iptables -A POSTROUTING -t mangle -p udp --dport bootpc -j CHECKSUM --checksum-fill";

# ]]]
# ]]]
# ]]]
